name: resnet18
train:
    batch_size: 24
    num_workers: 4
    csv_file: train.csv
    img_dir: .
    model_name: resnet18
    pretrained: True
    freeze: False
    lr: 0.3e-4
    load_cpk: False
    start_epoch: 0
    epochs: 100
    verbose_interval: 200
    save_period: 1
    result_dir: /content/drive/My Drive/cells-cells
    in_colab: True
    validation_split: 0.02
    shuffle_dataset: True
    enable_eval_on_val: True
    random_seed: 42
loss:
    global_coef: 5.
    local_coef: 10.
    verbose_interval: 20
    margin: 1. # before 0.3, empty for SoftMarginLoss
    topk_sigmoid: 30
test:
    use_leak: True
    csv_file: test.csv
    img_dir: .
    checkpoints_path: /content/drive/My Drive/cells-cells/checkpoint
    epoch: 6
    save_path: /content/drive/My Drive/cells-cells/submission.csv
    enable_eval: True
