train:
    batch_size: 16
    num_workers: 4
    csv_file: ../new_train.csv
    img_dir: ../train
    model_name: seresnext50
    freeze: False
    lr: 3e-4
    load_cpk: False
test:
    use_leak: True
    csv_file: ../new_test.csv
    img_dir: ../test
