name: seresnext50_resized
train:
    batch_size: 16
    num_workers: 4
    csv_file: train.csv
    img_dir: .
    model_name: seresnext50
    freeze: False
    lr: 0.3e-4
    load_cpk: False
    start_epoch: 0
    epochs: 100
    verbose_interval: 50
    save_period: 1
    result_dir: /content/drive/My Drive/cells-cells
    in_colab: True
    validation_split: 0.1
test:
    use_leak: True
    csv_file: test.csv
    img_dir: .
    checkpoints_path: /content/drive/My Drive/cells-cells/checkpoint
    epoch: 6
    save_path: /content/drive/My Drive/cells-cells/submission.csv
