name: seresnext50_resized
train:
    batch_size: 16
    num_workers: 4
    csv_file: ../new_train.csv
    img_dir: ../
    model_name: seresnext50
    freeze: False
    lr: 0.3e-4
    load_cpk: False
    epochs: 100
    verbose_interval: 50
    save_period: 1
    result_dir: /content/drive/cells-cells/
    in_colab: True
test:
    use_leak: True
    csv_file: ../new_test.csv
    img_dir: ../
